DEBUG_LOG_ON = True

CTK_APPEARANCE_MODE = "dark"
CTK_DEFAULT_COLOR_THEME = "dark-blue"

PADX = 30
PADY = 15

TEXT_FONT = ("Courier", 24)


HUB_LEFT_COLUMN_WIDTH = 100
HUB_LEFT_COLUMN_COLOR = "#212121"
HUB_MIDDLE_COLUMN_COLOR = "#1a1a1a"
HUB_RIGHT_COLUMN_WIDTH = 200
HUB_RIGHT_COLUMN_COLOR = "#212121"

HUB_FRAMES_PADX = 3
HUB_FRAMES_PADY = 3

MESSAGE_BACKGROUND_COLOR = "#212121"